enum OptionsLongNames {
    help = 'help',
    ignore = 'ignore',
    config = 'config',
    version = 'version',
    project = 'project',
    emptyKeys = 'emptyKeys',
    languages = 'languages',
    maxWarning = 'maxWarning',
    deepSearch = 'deepSearch',
    zombieKeys  = 'zombieKeys',
    keysOnViews = 'keysOnViews',
    misprintKeys = 'misprintKeys',
    fixZombiesKeys = 'fixZombiesKeys',
    frameworkPreset = 'frameworkPreset',
    misprintCoefficient = 'misprintCoefficient',
    duplicateKeys = 'duplicateKeys',
    missingTranslations = 'missingTranslations',
    fixMissingKeys = 'fixMissingKeys',
}

enum OptionsShortNames {
    ignore = 'i',
    config = 'c',
    project = 'p',
    version = 'v',
    languages = 'l',
    emptyKeys = 'ek',
    deepSearch = 'ds',
    zombieKeys = 'zk',
    keysOnViews = 'kv',
    misprintKeys = 'mk',
    fixZombiesKeys = 'fz',
    frameworkPreset = 'f',
    misprintCoefficient = 'mc',
    duplicateKeys = 'dk',
    missingTranslations = 'mt',
    fixMissingKeys = 'fm',
}

export { OptionsLongNames, OptionsShortNames };
